<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="actiTIME - Sanity"
           tests="6"
           failures="1"
           errors="0"
           skipped="0"
           time="45.176">
  <properties />
            <testcase name="TC05_CreateAUser" time="1.671" classname="com.actitime.testscripts.TestScripts">
                <failure type="java.lang.AssertionError"
                  message="expected [Sebastian, Andrew] but found [Angel, John]"
              >
<![CDATA[java.lang.AssertionError: expected [Sebastian, Andrew] but found [Angel, John]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:513)
  org.testng.Assert.assertEqualsImpl(Assert.java:135)
  org.testng.Assert.assertEquals(Assert.java:116)
  org.testng.Assert.assertEquals(Assert.java:190)
  org.testng.Assert.assertEquals(Assert.java:200)
  com.actitime.pageobjects.DashboardPO.createUser(DashboardPO.java:126)
  com.actitime.testscripts.TestScripts.TC05_CreateAUser(TestScripts.java:40)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:782)
  org.testng.TestRunner.run(TestRunner.java:632)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
  org.testng.SuiteRunner.run(SuiteRunner.java:268)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
  org.testng.TestNG.run(TestNG.java:1064)
  com.actitime.genericlibrary.XMLUtility.autoRunXml(XMLUtility.java:195)
  com.actitime.driver.Driver.main(Driver.java:19)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="TC01_SignIntoApplication" time="8.935" classname="com.actitime.testscripts.TestScripts" />
                <testcase name="TC02_NavigateToTasks" time="7.914" classname="com.actitime.testscripts.TestScripts" />
                <testcase name="TC07_SignOutOfApplication" time="7.985" classname="com.actitime.testscripts.TestScripts" />
                <testcase name="TC04_NavigateToUsers" time="10.175" classname="com.actitime.testscripts.TestScripts" />
                <testcase name="TC03_NavigateToReports" time="8.496" classname="com.actitime.testscripts.TestScripts" />
      
</testsuite>
