<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="W1650048" name="Default test" tests="7" failures="1" timestamp="4 Jan 2017 16:33:57 GMT" time="55.864" errors="0">
  <testcase name="TC01_SignIntoApplication" time="8.999" classname="com.actitime.testscripts.TestScripts"/>
  <testcase name="TC02_NavigateToTasks" time="8.203" classname="com.actitime.testscripts.TestScripts"/>
  <testcase name="TC03_NavigateToReports" time="9.342" classname="com.actitime.testscripts.TestScripts"/>
  <testcase name="TC04_NavigateToUsers" time="9.631" classname="com.actitime.testscripts.TestScripts"/>
  <testcase name="TC05_CreateAUser" time="1.582" classname="com.actitime.testscripts.TestScripts">
    <failure type="java.lang.AssertionError" message="expected [Gootam, Joshua] but found [Angel, John]">
      <![CDATA[java.lang.AssertionError: expected [Gootam, Joshua] but found [Angel, John]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.actitime.pageobjects.DashboardPO.createUser(DashboardPO.java:130)
	at com.actitime.testscripts.TestScripts.TC05_CreateAUser(TestScripts.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC05_CreateAUser -->
  <testcase name="TC06_VerifyExistingUser" time="10.433" classname="com.actitime.testscripts.TestScripts"/>
  <testcase name="TC07_SignOutOfApplication" time="7.635" classname="com.actitime.testscripts.TestScripts"/>
</testsuite> <!-- Default test -->
